on:
  issues:
    types: [opened, labeled, reopened]

permissions:
  issues: read
  repository-projects: write

jobs:
  add_to_project:
    runs-on: ubuntu-latest
    steps:
      - name: Add issue to Global QA board when labeled qa
        if: contains(github.event.issue.labels.*.name, 'qa')
        uses: actions/add-to-project@v1
        with:
          project-url: https://github.com/users/xG3R4RD0x/projects/4
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
